version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Vancouver
    volumes:
      - ./appdata:/config
      - ./data:/data
    ports:
      - 450:443
    restart: unless-stopped
