version: '3.3'
services:
    transmission-openvpn:
        volumes:
            - '/media:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - PUID=1000
            - PGID=1000
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=PIA #PROTONVPN #PIA
            - OPENVPN_CONFIG=us_california,switzerland,netherlands,us_seattle
            - OPENVPN_USERNAME=${OPENVPN_USERNAME} #see .env file
            - OPENVPN_PASSWORD=${OPENVPN_PASSWORD} #see .env file
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/24
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
            - TRANSMISSION_UMASK=0
            #- TRANSMISSION_WEB_UI=combustion
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        restart: unless-stopped
        image: haugene/transmission-openvpn:latest
