version: '3.3'
services:
    watchtower:
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        ports:
            - '8081:8080'
