version: "2.1"
services:
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - $HOME/containerData/NginxServer/config:/config
    ports:
      - 70:80
      - 442:443
    restart: unless-stopped

#version: '3'

#services:
#  server:
#    image: nginx:alpine
#    restart: always
#    ports:
#      - 70:80
#    volumes:
#      - $HOME/containerData/NginxServer/data/:/srv/
#      - $HOME/containerData/NginxServer/nginx.conf/:/etc/nginx/conf.d/
#default.conf

#networks:
 # default:
  #  external:
   #   name: yt-network
