version: '3'

services:
  server:
    image: nginx:alpine
    restart: always
    ports:
      - 70:80
    volumes:
      - ./Server/data/:/srv/
      - ./Server/nginx.conf:/etc/nginx/conf.d/default.conf

#networks:
 # default:
  #  external:
   #   name: yt-network
