version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ~/containerData/YTDownload/appdata:/app/appdata
            - ~/containerData/YTDownload/audio:/app/audio
            - ~/containerData/YTDownload/video:/app/video
            - ~/containerData/YTDownload/subscriptions:/app/subscriptions
            - ~/containerData/YTDownload/users:/app/users
        networks:
            - default
        ports:
            - "17442:17442"
        image: tzahi12345/youtubedl-material:latest

#networks:
 # default:
  #  external:
   #   name: yt-network
