version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - ./appdata:/app/appdata
            - ./audio:/app/audio
            - ./video:/app/video
            - ./subscriptions:/app/subscriptions
            - ./users:/app/users
        networks:
            - default
        ports:
            - "17442:17442"
        image: tzahi12345/youtubedl-material:latest

#networks:
 # default:
  #  external:
   #   name: yt-network
