version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
      #- PLEX_CLAIM= #optional
    volumes:
      - ~/containerData/plex/config:/config
      - /media/shows:/tv
      - /media/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
